trigger:
  - main  # or your preferred branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  pythonVersion: '3.10'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(pythonVersion)'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install Python Dependencies'

  - script: |
      echo "Packaging application files"
      mkdir -p $(Build.ArtifactStagingDirectory)/app
      cp app.py requirements.txt startup.txt $(Build.ArtifactStagingDirectory)/app
    displayName: 'Copy App Files'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/app'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/streamlit-app.zip'
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/streamlit-app.zip'
      ArtifactName: 'drop'
      publishLocation: 'Container'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: '<Your Azure Connection>'      # Replace with your service connection
      appName: '<Your App Service Name>'                # Replace with your web app name
      package: '$(Build.ArtifactStagingDirectory)/streamlit-app.zip'
      runtimeStack: 'PYTHON|3.10'
